In [ ]:
Accesing,changing and modifying arrays and copy,view arrays

In [1]:
import numpy as np
b=np.array([[1,2,3,4,5],[2,3,4,5,7]])
print(b)

[[1 2 3 4 5]
 [2 3 4 5 7]]


In [2]:
#variable(row,column)
b[1,4]
b[0,-1]
b[0,2]

3

In [18]:
#get a specific row
b[0,:]

array([1, 2, 3, 4, 5])

In [19]:
b[1,:]

array([2, 3, 4, 5, 7])

In [21]:
#get a specific colomn
b[:,4]

array([5, 7])

In [22]:
b[:,3]

array([4, 5])

In [23]:
#(startindex : endindex : stepsize)
b[0,0:4:2]

array([1, 3])

In [24]:
b[1,1:4:1]

array([3, 4, 5])

In [25]:
b[1,1:4]

array([3, 4, 5])

In [26]:
b[0,-1:0:2]

array([], dtype=int32)

In [27]:
b[0,-1:-5:2]

array([], dtype=int32)

In [28]:
b[0,-1:-5:-2]

array([5, 3])

In [3]:
b[0,0:-1:2]

array([1, 3])

In [31]:
b[1,4]=12
print(b)

[[ 1  2  3  4  5]
 [ 2  3  4  5 12]]


In [32]:
b[:,2]=5
print(b)

[[ 1  2  5  4  5]
 [ 2  3  5  5 12]]


In [33]:
b[1,:]=3
print(b)

[[1 2 5 4 5]
 [3 3 3 3 3]]


In [4]:
arr = np.array([1, 2, 3, 4, 5, 6, 7])

print(arr[::2])


[1 3 5 7]


In [9]:
a=np.array([[1,2,4,5,6],[3,4,5,6,9],[5,6,7,8,10]])
print(a)

[[ 1  2  4  5  6]
 [ 3  4  5  6  9]
 [ 5  6  7  8 10]]


In [16]:
a[0:3,1]

array([2, 4, 6])

In [17]:
a[0:3,1:4]

array([[2, 4, 5],
       [4, 5, 6],
       [6, 7, 8]])

In [39]:
#3d-example
c=np.array([[[1,2,3],[2,3,4],[4,5,6]],[[4,5,6],[9,8,7],[10,11,12]]])
print(c)

[[[ 1  2  3]
  [ 2  3  4]
  [ 4  5  6]]

 [[ 4  5  6]
  [ 9  8  7]
  [10 11 12]]]


In [40]:
c.ndim

3

In [41]:
c[0,1]

array([2, 3, 4])

In [42]:
c[1,1]

array([9, 8, 7])

In [43]:
c[0,2,2]

6

In [44]:
c[1,:]

array([[ 4,  5,  6],
       [ 9,  8,  7],
       [10, 11, 12]])

In [45]:
c[1,2,:]

array([10, 11, 12])

FOR COPY IN NUMPY WITH ANOTHER IS POSSSIBLE BUT IF ANY CHANGE IN ORIGINAL ARRAY IT DOES NOT AFFECT THE  COPIED ARRAY.

In [19]:
d=np.array([[1,2,3],[3,5,6]])
e=d.copy()
print(d)
print(e)

[[1 2 3]
 [3 5 6]]
[[1 2 3]
 [3 5 6]]


In [21]:
d[:,2]=[10,11]
print(d)

[[ 1  2 10]
 [ 3  5 11]]


In [22]:
print(e)

[[1 2 3]
 [3 5 6]]


BY USING VIEW() METHOD INSTEAD OF COPY() METHOD ,THE CHANGE IN ORIGINAL ARRAY CAN AFFECT THE NEWLY COPIED ARRAY

In [23]:
f=np.array([[1,2,3],[3,4,5]])
g=f.view()
print(f)
print(g)

[[1 2 3]
 [3 4 5]]
[[1 2 3]
 [3 4 5]]


In [24]:
f[:,0]=[3,3]
print(f)

[[3 2 3]
 [3 4 5]]


In [25]:
print(g)

[[3 2 3]
 [3 4 5]]
