Joining NumPy Arrays:

Joining means putting contents of two or more arrays in a single array.

In SQL we join tables based on a key, whereas in NumPy we join arrays by axes.

We pass a sequence of arrays that we want to join to the concatenate() function, along with the axis. If axis is not explicitly passed, it is taken as 0.

In [3]:
import numpy as np
arr1=np.array([1,2,3])
arr2=np.array([4,5,6])
#along x axis by default
join=np.concatenate((arr1,arr2))
print(join)

[1 2 3 4 5 6]


In [4]:
#along y axis use(axis=1)-rows concatenation
import numpy as np
arr1=np.array([[1,2,3],[4,5,9]])
arr2=np.array([[4,5,6],[6,7,8]])
join2=np.concatenate((arr1,arr2),axis=0)
print(join2)

[[1 2 3]
 [4 5 9]
 [4 5 6]
 [6 7 8]]


In [7]:
#by using stack() with axis
arr1=np.array([[1,2,3],[4,5,6]])
arr2=np.array([[4,5,6],[6,7,8]])
join=np.stack((arr1,arr2),axis=2)#(axis=1 or axis=0 or without any axis it prints the the same result)
print(join)


[[[1 4]
  [2 5]
  [3 6]]

 [[4 6]
  [5 7]
  [6 8]]]


In [9]:
#vertically stacking By Using the (vstack) stack along columns:

a=np.array([[1,2,3],[4,5,6]])
np.vstack(a)

array([[1, 2, 3],
       [4, 5, 6]])

In [10]:
#horizontal stacking by using the hstack() along rows:

np.hstack(a)

array([1, 2, 3, 4, 5, 6])

In [13]:
#Stacking Along Height (depth)
#NumPy provides a helper function: dstack() to stack along height, which is the same as depth.

np.dstack([arr1,arr2])

array([[[1, 4],
        [2, 5],
        [3, 6]],

       [[4, 6],
        [5, 7],
        [6, 8]]])