In [1]:
import numpy as np
arr=np.array([1,2,3,4,5])
x=[True,False,True,False,True]
newarr=arr[x]
print(newarr)

[1 3 5]


In [3]:
#creating an filter array
arr=np.array([1,2,3,4,5,6])
filter_arr=[]
for element in arr:
    if element>3:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr]
print(newarr)

[4 5 6]


In [6]:
#creating an filter array by our condition:
arr=np.array([2,5,8,9,4])
filter_arr=[]
for element in arr:
    if element%2==0:
        filter_arr.append(True)
    else:
        filter_arr.append(False)
newarr=arr[filter_arr]
print(newarr)

[2 8 4]


Creating Filter Directly From Array:

The above example is quite a common task in NumPy and NumPy provides a nice way to tackle it.

We can directly substitute the array instead of the iterable variable in our condition and it will work just as we expect it to.

In [9]:
arr=np.array([45,47,56,33])
filter_arr=arr>45
newarr=arr[filter_arr]
print(newarr)

[47 56]
