In [5]:
import numpy as np
#for searching use where() method:
arr=np.array([3,2,3,3,5,3])
np.where(arr==3)

(array([0, 2, 3, 5], dtype=int64),)

In [9]:
arr2=np.array([[1,4,3],[3,4,5]])
np.where(arr2==4)

(array([0, 1], dtype=int64), array([1, 1], dtype=int64))

In [16]:
#for printing even and odd numbers:
arr=np.array([1,2,3,4,5,6,7,9,10])
np.where(arr%2==0)

(array([1, 3, 5, 8], dtype=int64),)

In [17]:
np.where(arr%2==1)

(array([0, 2, 4, 6, 7], dtype=int64),)

In [18]:
#for seraching sorted arrays use searchsorted() method:
arr3=np.array([1,2,3,4,5,6])
np.searchsorted(arr3,3)

2

In [19]:
#search from the RIGHT SIDE:
np.searchsorted(arr3,3,side='right')

3

In [21]:
#to serach for more than one values:
#it will say the values where it to inserted to the arr4
arr4=np.array([1,3,5,7,9])
np.searchsorted(arr3,[2,4,6,10])

array([1, 3, 5, 6], dtype=int64)