In [1]:
import numpy as np
#FOR 1DIMENSIONAL ARRAY
a=np.array([1,2,3])
np.array_split(a,3)

[array([1]), array([2]), array([3])]

In [2]:
np.array_split(a,5)

[array([1]),
 array([2]),
 array([3]),
 array([], dtype=int32),
 array([], dtype=int32)]

In [7]:
#FOR 2 DIMENSIONAL ARRAY

b=np.array([[1,2,3],[2,4,6],[7,8,9]])
np.array_split(b,2)

[array([[1, 2, 3],
        [2, 4, 6]]),
 array([[7, 8, 9]])]

In [8]:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.array_split(arr, 3, axis=1)

print(newarr)

[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [9]:
#by using the hsplit opposite hsplit opposite of hstack:
import numpy as np

arr = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9], [10, 11, 12], [13, 14, 15], [16, 17, 18]])

newarr = np.hsplit(arr, 3)

print(newarr)


[array([[ 1],
       [ 4],
       [ 7],
       [10],
       [13],
       [16]]), array([[ 2],
       [ 5],
       [ 8],
       [11],
       [14],
       [17]]), array([[ 3],
       [ 6],
       [ 9],
       [12],
       [15],
       [18]])]


In [12]:
np.vsplit(arr,3)#oppposite of vertical stack

[array([[1, 2, 3],
        [4, 5, 6]]),
 array([[ 7,  8,  9],
        [10, 11, 12]]),
 array([[13, 14, 15],
        [16, 17, 18]])]