BASIC MATHEMATICS OPERATIONS ON NUMPY:

In [1]:
import numpy as np
a=np.array([1,2,3])
a+2

array([3, 4, 5])

In [2]:
a-2

array([-1,  0,  1])

In [3]:
a+2

array([3, 4, 5])

In [4]:
a*2

array([2, 4, 6])

In [5]:
a/2

array([0.5, 1. , 1.5])

In [6]:
b=np.array([3,4,5])
a+b

array([4, 6, 8])

In [7]:
arr1=np.ones((2,3))
arr2=np.full((3,4),3)
print(arr1)
print(arr2)

[[1. 1. 1.]
 [1. 1. 1.]]
[[3 3 3 3]
 [3 3 3 3]
 [3 3 3 3]]


In [8]:
np.matmul(arr1,arr2)

array([[9., 9., 9., 9.],
       [9., 9., 9., 9.]])

In [5]:
#determinant only appilacable for SQUARE MATRICES
import numpy as np
b2=np.array([[1,2],
             [3,7]])
np.linalg.det(b2)

0.9999999999999991

In [6]:
# Creating a matrix
A = np.array([[1, 2, 3],
              [4, 5, 6],
              [7, 8, 9]])

# Creating a vector
B = np.array([1, 2, 3])

In [8]:
#dot matrix multiplication
dot=np.dot(A,B)
print(dot)

[14 32 50]


In [10]:
# Matrix multiplication using @ operator
C_at = A @ B
print(C_at)

[14 32 50]


In [14]:
# Matrix inversion
A_inv = np.linalg.inv(b2)
print(A_inv)

[[ 7. -2.]
 [-3.  1.]]


Here are the general steps to find the inverse of a matrix:

Check Singularity:
Verify that the matrix is square (having the same number of rows and columns) and non-singular (determinant is non-zero).

Calculate the Adjoint:
Compute the adjoint of the matrix, denoted as 
adj
(
�
)
adj(A). The adjoint is obtained by taking the transpose of the cofactor matrix.

Calculate the Determinant:
Compute the determinant of the matrix 
det
⁡
(
�
)
det(A).

Compute the Inverse:
The inverse matrix is given by 
�
−
1
=
1
det
⁡
(
�
)
⋅
adj
(
�
)
A 
−1
 = 
det(A)
1
​
 ⋅adj(A).

In [23]:
#eg:
a=np.array([[1,2],[4,5]])
b=np.array([[4,5],[7,9]])
#check determinant:(must be square matrix)
np.linalg.det(a)

-2.9999999999999996

In [17]:
#inverse:
np.linalg.inv(a)

array([[-1.66666667,  0.66666667],
       [ 1.33333333, -0.33333333]])

In [19]:
# Transpose of a matrix
A_transpose = A.T
print(A_transpose)

[[1 4 7]
 [2 5 8]
 [3 6 9]]


In [20]:
# Eigenvalues and eigenvectors
eigenvalues, eigenvectors = np.linalg.eig(A)
print(eigenvalues, eigenvectors)

[ 1.61168440e+01 -1.11684397e+00 -1.30367773e-15] [[-0.23197069 -0.78583024  0.40824829]
 [-0.52532209 -0.08675134 -0.81649658]
 [-0.8186735   0.61232756  0.40824829]]


In [24]:
# Solving a system of linear equations: Ax = B
x = np.linalg.solve(a,b)
print(x)

[[-2.         -2.33333333]
 [ 3.          3.66666667]]
