In [1]:
import numpy as np
a=np.array([1,2,3])
print(a)

[1 2 3]


In [2]:
b=np.array([[1.2,1.3,5.6],[5.7,6.8,7.9]])
print(b)

[[1.2 1.3 5.6]
 [5.7 6.8 7.9]]


In [3]:
#get dimension
a.ndim

1

In [4]:
b.ndim

2

In [5]:
#get shape
a.shape

(3,)

In [6]:
b.shape

(2, 3)

In [7]:
#get type
a.dtype

dtype('int32')

In [8]:
b.dtype

dtype('float64')

In [9]:
a.dtype

dtype('int32')

In [28]:
#get single element size in bits
a=np.array([1,2,3],dtype="int16")
a.itemsize

2

In [29]:
#no of elements in an array
a.size

3

In [26]:
#total no of bits
a.itemsize*a.size

6

In [27]:
#Also total no of bits
a.nbytes

6

In [20]:
b.dtype

dtype('float32')

In [21]:
#get single element size in bits
b=np.array([[1.2,1.3,5.6],[5.7,6.8,7.9]],dtype="float32")
b.itemsize

4

In [22]:
#no of elements in an array
b.size

6

In [23]:
#total no of bits
b.itemsize*b.size

24

In [24]:
#Also total no of bits
b.nbytes

24