FOR ACCESING THE FILE DATA :

In [8]:
import numpy as np
#load data from the file by using the genfromtxt:
filedata=np.genfromtxt('forfiledata.txt',delimiter=',')
filedata

array([[ 1.,  2., 66.,  7.,  8.],
       [ 5., 77., 44.,  3.,  7.],
       [67.,  4.,  5.,  6., 55.]])

In [9]:
filedata.astype('int32')

array([[ 1,  2, 66,  7,  8],
       [ 5, 77, 44,  3,  7],
       [67,  4,  5,  6, 55]])

In [10]:
#boolean masking and advancedn indexing:
filedata>50

array([[False, False,  True, False, False],
       [False,  True, False, False, False],
       [ True, False, False, False,  True]])

In [14]:
filedata[filedata>50]


array([66., 77., 67., 55.])

In [3]:
import numpy as np
filedata=np.genfromtxt('forfiledata.txt',delimiter=',')
np.any(filedata>50,axis=0)

array([ True,  True,  True, False,  True])

In [4]:
np.any(filedata>50,axis=1)

array([ True,  True,  True])

In [6]:
#all the axis =0 will be greater than 50 so only it takes it as TRUE VALUE
np.all(filedata>50,axis=0)

array([False, False, False, False, False])

In [8]:
((filedata>50)&(filedata<100))

array([[False, False,  True, False, False],
       [False,  True, False, False, False],
       [ True, False, False, False,  True]])

In [9]:
(~(filedata>50)&(filedata<100))

array([[ True,  True, False,  True,  True],
       [ True, False,  True,  True,  True],
       [False,  True,  True,  True, False]])