In [ ]:
INTIALIZING ZEROS AND ONES AND RANDOM FUNCTIONS

In [3]:
import numpy as np
#2 dimensional zeros
np.zeros((2,3))

array([[0., 0., 0.],
       [0., 0., 0.]])

In [13]:
#3 dimensional zeros
np.zeros((5,3,5),dtype='int64')

array([[[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]],

       [[0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0],
        [0, 0, 0, 0, 0]]], dtype=int64)

In [20]:
#4 dimensional zeros
np.zeros((5,4,3,2),dtype='i')

array([[[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]]],


       [[[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
         [0, 0]],

        [[0, 0],
         [0, 0],
    

In [21]:
#2 dimensional ones
np.ones((2,3))

array([[1., 1., 1.],
       [1., 1., 1.]])

In [22]:
#3 dimensional ones
np.ones((2,3,4))

array([[[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]],

       [[1., 1., 1., 1.],
        [1., 1., 1., 1.],
        [1., 1., 1., 1.]]])

In [24]:
#4 dimensional
np.ones((3,4,2,3))

array([[[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]],


       [[[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]],

        [[1., 1., 1.],
         [1., 1., 1.]]]])

In [25]:
#get an any other number by usinf full
np.full((2,3),33)

array([[33, 33, 33],
       [33, 33, 33]])

In [27]:
np.full((3,2,3),33)

array([[[33, 33, 33],
        [33, 33, 33]],

       [[33, 33, 33],
        [33, 33, 33]],

       [[33, 33, 33],
        [33, 33, 33]]])

In [29]:
a=np.array([[1,2,3,10,11,13],[3,4,5,7,8,9]])
print(a)

[[ 1  2  3 10 11 13]
 [ 3  4  5  7  8  9]]


In [42]:
np.full(a.shape,3)

12


In [43]:
#get any number by using full_like method
np.full_like(a,3)

array([[3, 3, 3, 3, 3, 3],
       [3, 3, 3, 3, 3, 3]])

In [48]:
#get any number in the matrix by using the random functions
np.random.rand(2,3)

array([[0.36085335, 0.36168366, 0.96010133],
       [0.90495957, 0.7566939 , 0.38770293]])

In [49]:
np.random.rand(3,4,2)

array([[[0.43328228, 0.00223857],
        [0.74384646, 0.9329459 ],
        [0.34922808, 0.88117489],
        [0.79659409, 0.49042471]],

       [[0.23429814, 0.55372369],
        [0.23879268, 0.10365021],
        [0.90548114, 0.26743002],
        [0.73311798, 0.88636436]],

       [[0.01021391, 0.46710319],
        [0.35505715, 0.13903115],
        [0.11360098, 0.28919283],
        [0.38016681, 0.46305344]]])

In [52]:
#for passing an shape in random by using ramdom_sample
np.random.random_sample(a.shape)

array([[0.99693144, 0.40980783, 0.8045158 , 0.6092263 , 0.39071085,
        0.0521106 ],
       [0.65964282, 0.39131825, 0.29363539, 0.41582715, 0.24743205,
        0.62980853]])

In [54]:
print(a.size)

12


In [66]:
#get an integers from the random
np.random.randint(5,7,size=(2,3))

array([[6, 5, 5],
       [6, 6, 5]])

In [70]:
#for 1 dimensional repeat
arr=np.array([1,2,3])
r1=arr.repeat(3,axis=0)
print(r1)

[1 1 1 2 2 2 3 3 3]


In [79]:
#for 2 dimensional arrays
arr=np.array([[1,2,3]])
r2=arr.repeat(3,axis=0)
print(r2)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [80]:
#for identity matrix
np.identity(5)

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

#To crete an example matrix like:
     [[1,1,1,1,1]
      [1,0,0,0,1]
      [1,0,9,0,1]
      [1,0,0,0,1]
      [1,1,1,1,1]]


In [90]:
a=np.ones((5,5))
print(a)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [93]:
a[1,1:4]=[0,0,0]
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [98]:
a[2,1:4]=[0,9,0]
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [99]:
a[3,1:4]=[0,0,0]
print(a)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [102]:
#another method for this :
output=np.ones((5,5))
print(output)

[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]


In [104]:
b=np.zeros((3,3))
b[1,1]=9
print(b)


[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]


In [107]:
output[1:4,1:4]=b
print(output)

[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [108]:
#reshaping an array from 1d to 2d or to 3d
a=np.array([1,2,3,4,5,6])
a.reshape(2,3)

array([[1, 2, 3],
       [4, 5, 6]])

In [112]:
a=np.array([1,2,3,4,5,6,7,8,9,10,11,12])
a.reshape(3,2,2)

array([[[ 1,  2],
        [ 3,  4]],

       [[ 5,  6],
        [ 7,  8]],

       [[ 9, 10],
        [11, 12]]])