In [17]:
import numpy as np
np.empty((2,3),dtype='i')

array([[973435936,       611,         0],
       [        0,         1,         0]], dtype=int32)

In [20]:
print(np.linspace(1, 10, 3))

[ 1.   5.5 10. ]


In [21]:
print(np.linspace(1, 10, 10))

[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10.]


In [25]:
np.eye(4)#same as identity matrix

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [26]:
#Converting Array to List arr.tolist()
arr=np.array([1,2,3])
arr.tolist()

[1, 2, 3]

In [48]:
#creating files
np.save("for",np.arange(5))
#load on files
np.load("for.npy")
#importing a text file
np.loadtxt('file.txt',dtype='int32')
#importing csv files
np.genfromtxt('file.csv',delimiter=',')


FileNotFoundError: file.csv not found.

In [59]:
#write text file
arr=np.array([7,8,9,10],dtype='int32')
np.savetxt('write and save.txt',arr,delimiter=' ')

In [64]:
a=np.array([[5,3,1,9],[2,4,1,7]])
np.sort(a,axis=0)

array([[2, 3, 1, 7],
       [5, 4, 1, 9]])

In [65]:
arr = np.arange(1, 13).reshape(2, 6)
print("Original Array")
print(arr, "\n")

Original Array
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]] 



In [67]:
#create another array which is
#-to be appended column-wise
col = np.arange(5, 11).reshape(1, 6)
arr_col = np.append(arr, col, axis=0)
print("Array after appending the values column wise")
print(arr_col, "\n")

Array after appending the values column wise
[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]
 [ 5  6  7  8  9 10]] 



In [68]:
#-to be appended row wise
row = np.array([1, 2]).reshape(2, 1)
arr_row = np.append(arr, row, axis=1)
print("Array after appending the values row wise")
print(arr_row)

Array after appending the values row wise
[[ 1  2  3  4  5  6  1]
 [ 7  8  9 10 11 12  2]]


In [69]:
arr = np.asarray([1, 2, 3, 4])
#Python Program illustrating numpy.insert()
print("1D arr:", arr)
print("Shape:", arr.shape)
#Inserting value 9 at index 1
a = np.insert(arr, 1, 9)
print("\nArray after insertion:", a)

1D arr: [1 2 3 4]
Shape: (4,)

Array after insertion: [1 9 2 3 4]


In [71]:
#flatten array:
list_1 = [1, 2, 3, 4]
list_2 = [5, 6, 7, 8]
arr = np.array([list_1, list_2])
print(arr)

[[1 2 3 4]
 [5 6 7 8]]


In [72]:
print(arr.flatten())

[1 2 3 4 5 6 7 8]


IndexError: index 3 is out of bounds for axis 0 with size 2

In [80]:
a = np.array([[1 ,2 ],[3 ,4 ],[5 ,6 ]])
print(a[[0 ,1 ,2 ],[0 ,0 ,1]])#(rows,coloumns)


[1 3 6]


In [82]:
#comparison of arrays

an_array = np.array([[1, 2], [3, 4]])
another_array = np.array([[1, 2], [3, 4]])
comparison = an_array == another_array
equal_arrays = comparison.all()
print(equal_arrays)

True
