advanced random functions in numpy :


In [4]:
import numpy as np
#rand:
np.random.rand(5)
np.random.rand(2,4)

array([[0.3040188 , 0.35409366, 0.91975663, 0.70591083],
       [0.34760455, 0.1654109 , 0.61436629, 0.05067762]])

In [16]:
#randint:
np.random.randint(100,size=(2,2))

array([[64,  1],
       [87, 73]])

In [19]:
#choice:
np.random.choice([1,2,3,4,5],size=(2))

array([5, 3])