NumPy Set Operations:

What is a Set
A set in mathematics is a collection of unique elements.

Sets are used for operations involving frequent intersection, union and difference operations.

In [1]:
import numpy as np

#unique() method:

a=np.array([1,1,1,2,3,4,5,5,6,6,6])
np.unique(a)

array([1, 2, 3, 4, 5, 6])

In [2]:
# finding union - union1d()

a=np.array([1,2,3])
b=np.array([4,5,6])
np.union1d(a,b)

array([1, 2, 3, 4, 5, 6])

In [3]:
#finding intersection - intersect1d()

a=np.array([1,2,3])
b=np.array([3,2,6])
np.intersect1d(a,b)

array([2, 3])

In [2]:
#finding setdiffernce - setdiff1d()
#To find only the values in the first set that is NOT present in the seconds set, use the setdiff1d() method.

import numpy as np
a=np.array([1,2,3])
b=np.array([3,2,6])
np.setdiff1d(a,b,assume_unique=True)

array([1])

In [8]:
#finding symmteric differnce - setxor1d()
#Finding Symmetric Difference
#To find only the values that are NOT present in BOTH sets, use the setxor1d() method.

a=np.array([1,2,3])
b=np.array([3,2,6])
np.setxor1d(a,b,assume_unique=True)

array([1, 6])