NumPy Trigonometric Functions:

Trigonometric Functions
NumPy provides the ufuncs sin(), cos() and tan() that take values in radians and produce the corresponding sin, cos and tan values.

In [4]:
import numpy as np
np.sin(np.pi/2)

1.0

In [5]:
forsin=np.array([np.pi/2,np.pi/3,np.pi/4])
np.sin(forsin)

array([1.        , 0.8660254 , 0.70710678])

In [6]:
np.cos(np.pi/2)

6.123233995736766e-17

In [8]:
np.tan(45)

1.6197751905438615

Convert Degrees Into Radians:

By default all of the trigonometric functions take radians as parameters but we can convert radians to degrees and vice versa as well in NumPy.

Note: radians values are pi/180 * degree_values.

In [10]:
arr = np.array([90, 180, 270, 360])
np.deg2rad(arr)


array([1.57079633, 3.14159265, 4.71238898, 6.28318531])

Radians to Degrees:

In [11]:
arr = np.array([np.pi/2, np.pi, 1.5*np.pi, 2*np.pi])

x = np.rad2deg(arr)

print(x)

[ 90. 180. 270. 360.]


Finding Angles:

Finding angles from values of sine, cos, tan. E.g. sin, cos and tan inverse (arcsin, arccos, arctan).

NumPy provides ufuncs arcsin(), arccos() and arctan() that produce radian values for corresponding sin, cos and tan values given.

In [25]:
np.arcsin(0.7)

0.775397496610753

In [20]:
np.arccos(1.0)

0.0

In [24]:
np.arctan(1.0)

0.6107259643892086

In [22]:
#angles of each element in an array:

arr = np.array([1, -1, 0.1])

x = np.arcsin(arr)

print(x)

[ 1.57079633 -1.57079633  0.10016742]


Finding hypotenues using pythagoras theorem in NumPy.

NumPy provides the hypot() function that takes the base and perpendicular values and produces hypotenues based on pythagoras theorem.

In [23]:
base=4
perp=3
np.hypot(base,perp)


5.0