In [1]:
import numpy as np
arr=np.array([1,2,3])
np.prod(arr)

6

In [2]:
a=np.array([1,2,3])
b=np.array([5,4,3])
np.prod((a,b))

360

In [3]:
#according to axis=1:
np.prod((a,b),axis=1)

array([ 6, 60])

In [4]:
#cumulative product---1,1*2,1*2*3.
a=np.array([1,2,3])
np.cumprod(a)

array([1, 2, 6])

DIFFERENCE:
A discrete difference means subtracting two successive elements.

E.g. for [1, 2, 3, 4], the discrete difference would be [2-1, 3-2, 4-3] = [1, 1, 1]

To find the discrete difference, use the diff() function.

In [11]:
c=np.array([10,14,27,12])#(15-10,20-15)
np.diff(c)


array([  4,  13, -15])

In [7]:
d=np.array([1,2,3])
np.diff([c,d])

array([[5, 5],
       [1, 1]])

In [12]:
#Finding diffrence in 2 times :
np.diff(c,n=2)

array([  9, -28])