Simple Arithmetic:
You could use arithmetic operators + - * / directly between NumPy arrays, but this section discusses an extension of the same where we have functions that can take any array-like objects e.g. lists, tuples etc. and perform arithmetic conditionally.

In [3]:
import numpy as np
a=np.array([1,2,3])
b=np.array([5,6,7])
np.add(a,b)


array([ 6,  8, 10])

In [4]:
np.subtract(a,b)

array([-4, -4, -4])

In [5]:
np.multiply(a,b)

array([ 5, 12, 21])

In [6]:
np.divide(a,b)

array([0.2       , 0.33333333, 0.42857143])

In [7]:
np.remainder(a,b)

array([1, 2, 3])

In [8]:
np.mod(a,b)

array([1, 2, 3])

In [9]:
np.divmod(a,b)

(array([0, 0, 0]), array([1, 2, 3]))

In [10]:
np.power(a,b)

array([   1,   64, 2187])

In [12]:
c=np.array([-3,-5,-8])
np.absolute(c)

array([3, 5, 8])

In [13]:
np.abs(c)

array([3, 5, 8])