Logs:

NumPy provides functions to perform log at the base 2, e and 10.

We will also explore how we can take log for any base by creating a custom ufunc.

All of the log functions will place -inf or inf in the elements if the log can not be computed.

In [2]:
import numpy as np
#log at base 2
arr=np.arange(1,11)
np.log2(arr)

array([0.        , 1.        , 1.5849625 , 2.        , 2.32192809,
       2.5849625 , 2.80735492, 3.        , 3.169925  , 3.32192809])

In [3]:
#log at base 10:
np.log10(arr)

array([0.        , 0.30103   , 0.47712125, 0.60205999, 0.69897   ,
       0.77815125, 0.84509804, 0.90308999, 0.95424251, 1.        ])

In [4]:
#log at base e:
np.log(arr)

array([0.        , 0.69314718, 1.09861229, 1.38629436, 1.60943791,
       1.79175947, 1.94591015, 2.07944154, 2.19722458, 2.30258509])

In [10]:
#log at any base:
from math import log
mylog=np.frompyfunc(log,2,1)
print(mylog(100,120))

0.9619171026103941
