Rounding Decimals
There are primarily five ways of rounding off decimals in NumPy:

truncation
fix
rounding
floor
ceil

In [2]:
import numpy as np
#truncation - trunc() or fix()
#Remove the decimals, and return the float number closest to zero. Use the trunc() and fix() functions.
#truncation return the values as INTEGER !!!!!!!
np.trunc([-3.44,5.5])


array([-3.,  5.])

In [3]:
#fix() also same as trunc()
np.fix([-3.44,5.5])

array([-3.,  5.])

In [5]:
#Rounding

#The around() function increments preceding digit or decimal by 1 if >=5 else do nothing.

#E.g. round off to 1 decimal point, 3.16666 is 3.2

#Example
np.around([-3.44,5.5])

array([-3.,  6.])

In [6]:
#floor

#The floor() function rounds off decimal to nearest lower integer.

#E.g. floor of 3.166 is 3.
np.floor([-3.44,5.5])

array([-4.,  5.])

In [7]:
#Ceil

#The ceil() function rounds off decimal to nearest upper integer.

#E.g. ceil of 3.166 is 4.
np.ceil([-3.44,5.5])

array([-3.,  6.])